### ISSUE TITLE
How to specify granularity to Kline/Candlestick Streams?

### ISSUE THREAD

**Issue by 5erpens** [coinbase/coinbase-advanced-py#46]
How to specify granularity to Kline/Candlestick Streams?
For example, in [Binance](https://binance-docs.github.io/apidocs/spot/en/#kline-candlestick-streams) or in [KuCoin](https://www.kucoin.com/docs/websocket/spot-trading/public-channels/klines) have something like this.

**Comment by urischwartz-cb** [comment]
Hi @5erpens, you can specify granularity for candles in our GetCandles REST endpoint as described in our docs [here](https://docs.cloud.coinbase.com/advanced-trade/reference/retailbrokerageapi_getcandles).

Our Websocket candles channel returns updates in buckets of 5 minutes as described [here](https://docs.cloud.coinbase.com/advanced-trade/docs/ws-channels#candles-channel). 

Since this is an API related question, rather than SDK specific, please reach out on [our discord](https://discord.com/channels/1220414409550336183/1220464268743278613) if you wish to follow up on this. Thank you!

**Comment by urischwartz-cb** [comment]
@5erpens yes this is the link: https://discord.com/channels/1220414409550336183/1220464268743278613

Does that not work for you?

**Comment by urischwartz-cb** [comment]
Could you try just this link: https://discord.com/channels/1220414409550336183
That's the link to the Coinbase Developer Platform server, of which Advanced API is a sub-channel. If that doesn't work let me know and I will raise to the team.

**Comment by urischwartz-cb** [comment]
@5erpens can you try going through this invite link first: https://discord.com/invite/cdp
