### ISSUE TITLE
How can I get the USD balance for crypto trading?

### ISSUE THREAD

**Issue by scottgl9** [coinbase/coinbase-advanced-py#82]
I noticed that USD is not listed:
client = RestClient(...)
print(client.get_accounts())

What is the correct way to get the USD balance of the account? Is the only method with get_futures_balance_summary()?

**Comment by scottgl9** [comment]
Also how can I get USDC balance?

**Comment by urischwartz-cb** [comment]
If you have USD or USDC in your account, these should show up as individual accounts in the GetAccounts response. Make sure if you have over 49 accounts to paginate or pass a higher `limit` in your request to get more accounts listed in the response.

If that does not work for you still, please reach out in the Discord linked above as we can help you more directly with your API questions since this does not seem specifically related to the SDK.
